'use server';

import { PrismaClient } from '@prisma/client';
import nodemailer from 'nodemailer';

const prisma = new PrismaClient();

export type LeadResponse = {
  success: boolean;
  message?: string;
  leadId?: string;
};

export async function processMortgageLead(formData: FormData): Promise<LeadResponse> {
  try {
    const full_name = formData.get('full_name') as string;
    const phone = formData.get('phone') as string;
    const employer_type = formData.get('employer_type') as string;
    const rsa_balance_str = formData.get('rsa_balance') as string;
    const years_in_work_str = formData.get('years_in_work') as string;
    const years_to_retire_str = formData.get('years_to_retire') as string;
    const branch_id = formData.get('branch_id') as string;
    const pfa_id = formData.get('pfa_id') as string;

    if (!full_name || !phone || !rsa_balance_str || !branch_id || !pfa_id || !years_in_work_str || !years_to_retire_str) {
      return { success: false, message: 'Missing required fields' };
    }

    const rsa_balance = parseFloat(rsa_balance_str);
    const years_in_work = parseInt(years_in_work_str, 10);
    const years_to_retire = parseInt(years_to_retire_str, 10);
    if (isNaN(rsa_balance) || isNaN(years_in_work) || isNaN(years_to_retire)) {
      return { success: false, message: 'Invalid numeric fields' };
    }

    // 1. Resolve PFA Rule (try by ID, then by name); if unrecognized, record it
    //    on the fly rather than blocking the lead from reaching the admin panel.
    let pfaRule = await prisma.pfaRule.findUnique({
      where: { id: pfa_id },
    });
    if (!pfaRule) {
      pfaRule = await prisma.pfaRule.findUnique({
        where: { name: pfa_id },
      });
    }
    if (!pfaRule) {
      pfaRule = await prisma.pfaRule.create({
        data: { name: pfa_id || 'Unspecified PFA', minimum_threshold: 0 },
      });
    }

    // 2. Resolve Branch (try by ID, then by name); fall back to the first
    //    branch on record so a lead is never dropped over a branch mismatch.
    let branch = await prisma.branch.findUnique({
      where: { id: branch_id },
    });
    if (!branch) {
      branch = await prisma.branch.findUnique({
        where: { name: branch_id },
      });
    }
    if (!branch) {
      branch = await prisma.branch.findFirst({ orderBy: { name: 'asc' } });
    }
    if (!branch) {
      return { success: false, message: 'No branches are configured yet. Please contact support directly.' };
    }

    // 3. Strict Server-Side Mathematical Validation
    const is_eligible = years_in_work >= 5 && years_to_retire >= 3;

    // 4. Save to Database
    const lead = await prisma.lead.create({
      data: {
        full_name,
        phone,
        employer_type: employer_type || 'Unknown',
        rsa_balance,
        years_in_work,
        years_to_retire,
        is_eligible,
        pfa_id: pfaRule.id,
        branch_id: branch.id,
      },
    });

    // 5. Send Notification Email
    try {
      if (process.env.SMTP_USER && process.env.SMTP_PASS) {
        const transporter = nodemailer.createTransport({
          host: process.env.SMTP_HOST || 'smtp.gmail.com',
          port: parseInt(process.env.SMTP_PORT || '587', 10),
          secure: process.env.SMTP_SECURE === 'true',
          auth: {
            user: process.env.SMTP_USER,
            pass: process.env.SMTP_PASS,
          },
        });

        await transporter.sendMail({
          from: `"Trust Bricks Automations" <${process.env.SMTP_USER}>`,
          to: 'customerservice@trustbrickspropertieslimited.com.ng',
          subject: `New Mortgage Lead - ${full_name}`,
          html: `
            <h2>New Mortgage Lead Submitted</h2>
            <p><strong>Name:</strong> ${full_name}</p>
            <p><strong>Phone:</strong> ${phone}</p>
            <p><strong>Employer Type:</strong> ${employer_type}</p>
            <p><strong>RSA Balance:</strong> ₦${rsa_balance.toLocaleString('en-NG')}</p>
            <p><strong>Years in Service:</strong> ${years_in_work}</p>
            <p><strong>Years to Retire:</strong> ${years_to_retire}</p>
            <p><strong>Eligible:</strong> <span style="color: ${is_eligible ? 'green' : 'red'}">${is_eligible ? 'Yes' : 'No'}</span></p>
            <p><strong>Preferred Branch:</strong> ${branch.name}</p>
            <p><strong>PFA:</strong> ${pfaRule.name}</p>
            <hr />
            <p><small>This email was automatically generated by the Trust Bricks system.</small></p>
          `,
        });
        console.log('[ROUTING ENGINE] Notification email sent to customer service.');
      } else {
        console.warn('[ROUTING ENGINE] SMTP credentials not configured. Email skipped.');
      }
    } catch (emailErr) {
      console.error('[ROUTING ENGINE] Failed to send email:', emailErr);
    }

    console.log(`[ROUTING ENGINE] Lead ${lead.id} routed to ${branch.name}. Eligible: ${is_eligible}`);

    return {
      success: true,
      leadId: lead.id,
      message: is_eligible 
        ? 'You meet the PenCom requirements for the RSA equity contribution scheme.'
        : 'Your current RSA balance does not meet the minimum threshold set by your PFA.',
    };

  } catch (error: any) {
    console.error('[LEAD ROUTING ERROR]', error);
    return {
      success: false,
      message: 'An unexpected error occurred while processing your lead.',
    };
  }
}
